### ISSUE TITLE
fails to install from pip

### ISSUE THREAD

**Issue by anarcat** [chaica/feed2tweet#2]
i may be doing something wrong here, but i can't seem to install this thing through pip as suggested in the readme:

```
$ pip install feed2tweet
Downloading/unpacking feed2tweet
  Could not find any downloads that satisfy the requirement feed2tweet
Cleaning up...
No distributions at all found for feed2tweet
Storing debug log for failure in /home/anarcat/.pip/pip.log
```

the debug log says:

```
-----------------------------------------------------------
/usr/bin/pip run on Tue Dec 29 01:18:14 2015
Downloading/unpacking feed2tweet
  Getting page https://pypi.python.org/simple/feed2tweet/
  Could not fetch URL https://pypi.python.org/simple/feed2tweet/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/feed2tweet/ when looking for download links for feed2tweet
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for feed2tweet:
  * https://pypi.python.org/simple/feed2tweet/
  Getting page https://pypi.python.org/simple/feed2tweet/
  Could not fetch URL https://pypi.python.org/simple/feed2tweet/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/feed2tweet/ when looking for download links for feed2tweet
  Could not find any downloads that satisfy the requirement feed2tweet
Cleaning up...
No distributions at all found for feed2tweet
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for feed2tweet
```

indeed, the package doesn't exist on pypi: https://pypi.python.org/pypi?%3Aaction=search&term=feed2tweet&submit=search

**Comment by chaica** [comment]
Hi and thanks for the bug report,

The release was a mess, sorry for that. I just uploaded feed2tweet 0.1 on PyPI.

Cheers,
Carl

**Comment by anarcat** [comment]
great, thanks!
