### ISSUE TITLE
KeyError: 'tags'

### ISSUE THREAD

**Issue by mytuxfr** [chaica/feed2tweet#22]
```
unexpected exception
Traceback (most recent call last):
  File "./feed2tweet", line 173, in <module>
    main()
  File "./feed2tweet", line 144, in main
    prehashtags = entry['tags'][0]['term']
  File "/usr/local/lib/python3.4/dist-packages/feedparser.py", line 357, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'tags'
Traceback (most recent call last):
  File "./feed2tweet", line 173, in <module>
    main()
  File "./feed2tweet", line 144, in main
    prehashtags = entry['tags'][0]['term']
  File "/usr/local/lib/python3.4/dist-packages/feedparser.py", line 357, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'tags'
```

**Comment by chaica** [comment]
improper fix - should be rewritten
