### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by chaica** [chaica/feed2tweet#42]
Feed2tweet crashes on this rss feed https://www.mongodb.com/blog/rss
```
Traceback (most recent call last):
  File "/usr/local/bin/feed2tweet", line 24, in <module>
    Main()
  File "/usr/local/lib/python3.4/dist-packages/feed2tweet/main.py", line 43, in __init__
    self.main()
  File "/usr/local/lib/python3.4/dist-packages/feed2tweet/main.py", line 81, in main
    if i['id'] not in cache:
  File "/usr/local/lib/python3.4/dist-packages/feedparser.py", line 357, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'id'
```

**Comment by chaica** [comment]
It's not a feed2tweet bug, but an issue with the malformed rss feed entry missing the id field. will be fixed in 1.0.
