### ISSUE TITLE
UnboundLocalError: local variable 'severalwordshashtags' referenced before assignment

### ISSUE THREAD

**Issue by gdamjan** [chaica/feed2tweet#53]
Running 1.1, I get this traceback (config file below):
```
Traceback (most recent call last):
  File "py-env/bin/feed2tweet", line 24, in <module>
    Main()
  File "/home/damjan/py-env/lib/python3.6/site-packages/feed2tweet/main.py", line 44, in __init__
    self.main()
  File "/home/damjan/py-env/lib/python3.6/site-packages/feed2tweet/main.py", line 131, in main
    for element in severalwordshashtags:
UnboundLocalError: local variable 'severalwordshashtags' referenced before assignment
```
config:
```
[cache]
cachefile=~/cache.db
cache_limit=10000

[rss]
uri=http://feeds.feedburner.com/spodeliznaenje
tweet={title} {link}

[twitter]
...
```

seems that `severalwordshashtags` in unitialized when not using the `hashtaglist` option.
initializing it to an empty list on [feed2tweet/main.py#L78](https://github.com/chaica/feed2tweet/blob/master/feed2tweet/main.py#L78) fixes the issue

**Comment by chaica** [comment]
Hi and thanks for your bug report. You need a [hashtaglist] section in your .ini Have a look at [the official documentation](http://feed2tweet.readthedocs.io/en/latest/configure.html).
```
For the [hashtaglist] section:

    several_words_hashtags_list: a path to the file containing hashtags in two or more words. Absolute path is mandatory. By default Feed2tweet adds a # before every words of a hashtag.
```
Create this file and put the following content in it:
```
Open Source
Free Software
```

The mandatory file will be removed from the next version of Feed2tweet.

Regards,
Carl

**Comment by gdamjan** [comment]
I didn't understand it's mandatory (I understood it as full path is mandatory - if used).

What does this option mean, actually??

**Comment by chaica** [comment]
it smartly manages the tags from your rss feeds which don't have the format that expect Twitter, e.g 
open source => #open #source 
if you put open source in this file you get #opensource
the same with sugar free => #sugar #free 
if you sugar free in this file you get #sugarfree
